import { useEffect, useRef, useState } from 'react'
import { AnimatePresence, motion, useScroll, useSpring } from 'framer-motion'
import { photos, reasons, story, timeline } from './content'
import './photo.css'

const rise = { initial: { opacity: 0, y: 26 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: .22 }, transition: { duration: .7 } }
const Hearts = ({ count = 18 }) => <div className="hearts" aria-hidden="true">{Array.from({ length: count }, (_, i) => <i key={i} style={{ '--x': `${(i * 17 + 3) % 100}%`, '--d': `${5 + (i % 6)}s`, '--delay': `${-(i % 7)}s` }}>{i % 3 ? '♥' : '✦'}</i>)}</div>

function MusicPlayer() {
  const audio = useRef(null); const [playing, setPlaying] = useState(false); const [progress, setProgress] = useState(0); const [unavailable, setUnavailable] = useState(false)
  const toggle = async () => { if (!audio.current) return; try { if (playing) audio.current.pause(); else await audio.current.play(); setPlaying(!playing) } catch { setUnavailable(true) } }
  return <motion.div className="music glass" {...rise}><div className="equalizer" aria-hidden="true">{[1,2,3,4].map(n => <i className={playing ? 'play' : ''} key={n}/>)}</div><div className="song"><small>NOW PLAYING</small><b>{story.song.title}</b><span>{unavailable ? 'Add your song to public/assets to play it' : 'A little melody for us'}</span></div><button onClick={toggle} aria-label={playing ? 'Pause song' : 'Play song'}>{playing ? 'Ⅱ' : '▶'}</button><input aria-label="Song progress" type="range" min="0" max="100" value={progress} onChange={e => { if(audio.current?.duration) audio.current.currentTime = audio.current.duration * e.target.value / 100 }} /><audio ref={audio} src={story.song.src} onTimeUpdate={e => setProgress(e.currentTarget.duration ? e.currentTarget.currentTime / e.currentTarget.duration * 100 : 0)} onEnded={() => setPlaying(false)} onError={() => setUnavailable(true)} /></motion.div>
}

function Cake() { return <div className="cake" aria-label="Birthday cake"><div className="flame">♨</div><div className="candle"/><div className="icing">♥</div><div className="tier"/><div className="tier lower"/></div> }

export default function App() {
  const [opened, setOpened] = useState(false), [letter, setLetter] = useState(false), [final, setFinal] = useState(false), [selected, setSelected] = useState(null), [expandedPhoto, setExpandedPhoto] = useState(null)
  const { scrollYProgress } = useScroll(); const scaleX = useSpring(scrollYProgress, { stiffness: 80, damping: 22 })
  useEffect(() => { document.body.classList.toggle('locked', !opened); return () => document.body.classList.remove('locked') }, [opened])
  return <><motion.div className="journey" style={{ scaleX }} /><AnimatePresence>{!opened && <motion.section className="opening" exit={{ opacity: 0, scale: 1.05 }} transition={{ duration: .8 }}><Hearts count={12}/><div className="opening-copy"><span className="eyebrow">FOR RUHI · WITH ALL MY HEART</span><p className="opening-mark">♥</p><h1>{story.opening}</h1><p>Come closer. I made a little world, filled with the moments that feel like us.</p><button className="primary" onClick={() => setOpened(true)}>Open Your Surprise <span>→</span></button></div></motion.section>}</AnimatePresence>
  <main className={opened ? 'story live' : 'story'}>
    <Hearts/>
    <section className="hero"><div className="hero-orbit"/><motion.div initial={{opacity:0,y:18}} animate={opened ? {opacity:1,y:0} : {}} transition={{delay:.25,duration:.8}}><span className="eyebrow">A birthday story · written in little moments</span><p className="pretitle">Happy Birthday</p><h2>My Love,<br/><em>{story.name} ♥</em></h2><p className="hero-copy">For the girl who made my ordinary life feel beautifully extraordinary.</p><Cake/><a href="#memories" className="scroll-cue">Begin our story <span>↓</span></a></motion.div></section>
    <nav><span>Y ♥ Y</span><a href="#memories">Memories</a><a href="#letter">A letter</a><a href="#finale">Forever</a></nav>
    <div className="content">
      <motion.section id="memories" className="section" {...rise}><span className="eyebrow">CHAPTER ONE</span><h2>Our little timeline</h2><p className="intro">Some dates hold more than a day. They hold laughter, feelings, and a little bit of forever.</p><div className="timeline">{timeline.map((item, i) => <motion.article className="timeline-item glass" key={item.date} {...rise} transition={{delay:i*.08,duration:.55}}><span className="dot">♥</span><small>{item.date}</small><h3>{item.title}</h3><p>{item.detail}</p></motion.article>)}</div></motion.section>
      <motion.section className="section" {...rise}><span className="eyebrow">CHAPTER TWO</span><h2>Photo memories</h2><p className="intro">Tiny frames waiting for our biggest feelings.</p><div className="gallery">{photos.map((photo, i) => { const expanded = expandedPhoto === i; const note = expanded ? photo.detail : `${photo.detail?.slice(0, 145) || ''}${photo.detail?.length > 145 ? '…' : ''}`; return <button className={'polaroid p'+i} key={photo.caption} onClick={() => setSelected(photo)}><div className="photo-space">{photo.src ? <img src={photo.src} alt={photo.caption}/> : <><span>♥</span><small>ADD OUR PHOTO</small></>}</div><time>{photo.date}</time><b>{photo.caption}</b>{photo.detail && <><p style={{ margin: '8px 2px 0', color: '#7d3852', fontSize: '.72rem', lineHeight: 1.65, fontFamily: 'Hind Vadodara, sans-serif', whiteSpace: 'pre-line' }}>{note}</p><span role="button" tabIndex={0} onClick={event => { event.stopPropagation(); setExpandedPhoto(expanded ? null : i) }} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); event.stopPropagation(); setExpandedPhoto(expanded ? null : i) } }} style={{ display: 'inline-block', marginTop: 10, color: '#b12f67', fontSize: '.74rem', fontWeight: 700, textDecoration: 'underline' }}>{expanded ? 'ટૂંકું વાંચો ↑' : 'વધુ વાંચો ♥'}</span></>}</button>})}</div></motion.section>
      <motion.section className="section" {...rise}><span className="eyebrow">CHAPTER THREE</span><h2>Why you are special to me <span className="pink">♥</span></h2><div className="reasons">{reasons.map(([icon, title, copy]) => <motion.button className="reason glass" whileTap={{scale:.96, rotate:-1}} key={title}><i>{icon}</i><h3>{title}</h3><p>{copy}</p></motion.button>)}</div></motion.section>
      <motion.section id="letter" className="section letter-section" {...rise}><span className="eyebrow">CHAPTER FOUR</span><h2>A secret, just for you</h2><button className={'envelope '+(letter ? 'open' : '')} onClick={() => setLetter(!letter)} aria-expanded={letter}><div className="flap"/><div className="envelope-heart">♥</div><span>{letter ? 'A love letter, opened' : 'Open this letter ♥'}</span></button><AnimatePresence>{letter && <motion.article className="love-letter" initial={{opacity:0,y:-30,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-20}}><p>{story.loveLetter}</p></motion.article>}</AnimatePresence></motion.section>
      <MusicPlayer/>
    </div>
    <section id="finale" className="finale"><div className="fireworks" aria-hidden="true"><i/><i/><i/></div><Hearts count={25}/><motion.div className="final-copy" {...rise}><span className="eyebrow">THE END OF THIS PAGE · NOT OUR STORY</span><h2>Happy Birthday<br/><em>{story.name} ♥</em></h2><p>તારી સાથે વિતાવેલી દરેક પળ મારા માટે ખાસ છે,<br/>અને મારી સૌથી સુંદર યાદોમાં તું હંમેશા રહેશે.</p><button className="primary" onClick={() => setFinal(true)}>One Last Surprise ♥</button><AnimatePresence>{final && <motion.p className="last-message" initial={{opacity:0,y:14}} animate={{opacity:1,y:0}}>{story.finalMessage}</motion.p>}</AnimatePresence></motion.div></section>
  </main><AnimatePresence>{selected && <motion.div className="modal" onClick={() => setSelected(null)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="modal-card" onClick={e=>e.stopPropagation()}><button onClick={() => setSelected(null)}>×</button><div className="modal-photo">{selected.src ? <img src={selected.src} alt="Memory"/> : '♥'}</div><small>{selected.date}</small><h3>{selected.caption}</h3></div></motion.div>}</AnimatePresence></>
}
